//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager_Medias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album_Details
    {
        public int Id { get; set; }
        public Nullable<int> IdAlbum { get; set; }
        public string Image { get; set; }
    
        public virtual Album Album { get; set; }
    }
}
