//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager_Medias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int Id { get; set; }
        public Nullable<int> IdCategory { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<double> IMDB { get; set; }
        public string Poster { get; set; }
        public Nullable<int> Likes { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> NumberOfViews { get; set; }
        public string Video { get; set; }
        public string Season { get; set; }
        public string Time { get; set; }
    
        public virtual Media Media { get; set; }
        public virtual Movie_Categories Movie_Categories { get; set; }
    }
}
