//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager_Medias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_History
    {
        public string Email { get; set; }
        public Nullable<System.DateTime> DateOfPayment { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int Id { get; set; }
    
        public virtual User User { get; set; }
    }
}
